
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Asp.NETMVCCRUD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CarDetail
{

    public int Id { get; set; }

    public int CarId { get; set; }

    public string PlateNumber { get; set; }

    public string Model { get; set; }

    public string Colour { get; set; }

    public string Description { get; set; }

}

}
